[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fake-library-python"
version = "0.1.0"
description = "Python library that subclasses Cython bindings"
requires-python = ">=3.10"
dependencies = ["fake-library-bindings"]

[tool.setuptools.packages.find]
include = ["fake_library_python*"]
